#![no_std]   // do not link the Rust std library
#![no_main]  // disable all Rust-level entry points
#![feature(custom_test_frameworks)]   // replace the default test framework which relies on std lib
#![test_runner(crate::test_runner)]
// the custom test framework feature generates a main function that calls test_runner, which is ignored by `![no_main]`
#![reexport_test_harness_main = "test_main"]

// use core::fmt::Write;
use core::panic::PanicInfo;

mod vga_buffer;

#[no_mangle] // do not mangle the name of this function
pub extern "C" fn _start() -> ! {
    println!("Hello World{}", "!");

    // this will only be included for tests, and `test_main` function will be generated by the custom_test_frameworks feature
    #[cfg(test)]
    test_main();

    loop {}
}

/// This function is called on panic
#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    println!("{}", info);
    loop {}
}

// include this function only for tests
#[cfg(test)]
// &[&dyn Fn()] a slice of trait object references of the Fn() trait  -> the slice will contains references to function marked as test_case
// It is a list of references to types that can be called like a function
pub fn test_runner(tests: &[&dyn Fn()]) {
    println!("Running {} tests", tests.len());
    for test in tests {
        test();
    }
}

#[test_case]
fn trivial_assertion() {
    print!("trivial assertion...");
    assert_eq!(2, 1);
    println!("[ok]");
}
